### ISSUE TITLE
python3 PyBER.py data.refs.readers

### ISSUE THREAD

**Issue by marielacbv** [aff3ct/PyBER#4]
Hi,

While launching:

python3 PyBER.py

I encountered the following issue:
```
===== 2019.10.14 16:10:56 =====
Traceback (most recent call last):
File "PyBER.py", line 31, in
import fileExplorer
File "/home/mbaron/aff3ct/PyBER-master/fileExplorer.py", line 25, in
from data.refs.readers.aff3ct_trace_reader import aff3ctTraceReader
ModuleNotFoundError: No module named 'data.refs.readers'
```

thanks

**Comment by kouchy** [comment]
It looks like you did not get the Git sub-modules. Try to get the sub-modules by calling `git submodules update --init --recursive` in the root directory of the PyBER repo.

**Comment by Shivani3094** [comment]
Hi,

I have followed the instructions as mentioned in above linked comment. After using the comment "git submodule update --init --recursive" i have tried to run the comment "python PyBER.py". But i am still facing the following issue:

**_===== 2019.11.12 15:11:02 =====
Traceback (most recent call last):
  File "PybER.py", line 31, in <module>
    import fileExplorer
  File "C:\Project\aff3ct\PyBER-master\fileExplorer.py", line 25, in <module>
    from data.refs.readers.aff3ct_trace_reader import aff3ctTraceReader
ModuleNotFoundError: No module named 'data.refs.readers'_**

Thanks
