### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by Shivani3094** [aff3ct/PyBER#5]
Hi, i have downloaded Anaconda 2019 10 with Python version 3.7. I have tried installing PyBER on windows but unable to do so.
Can you let me know the process to do so on windows?

**Comment by kouchy** [comment]
Hi @Shivani3094,

Could you give us your error messages? And tell us what you have done exactly? What is your Windows version?

**Comment by Shivani3094** [comment]
I am currently using the library with Windows 10. I have installed Anaconda and tried to run the command "python PyBER.py" in Anaconda Prompt and facing error as follows:

**_Traceback (most recent call last):
  File "PyBER.py", line 26, in <module>
    import lib.pyqtgraph.pyqtgraph.console
ModuleNotFoundError: No module named 'lib.pyqtgraph.pyqtgraph'_**

My Python version is 3.7. I have added python to the Environment variables of my account. Apart from that to resolve the above issue i have installed "pyqtgraph" using the following command:
**_pip install pyqtgraph_**

But inspite of that i am facing the same error as above.

**Comment by kouchy** [comment]
It looks like you do not have the `pyqtgraph` dependency in your repository. Did you clone the repository? If not, you have to. Once you have clone the repository you have to get `pyqtgraph`, which is a Git sub-module of the `PyBER` repository, by doing: `git submodule update --init --recursive`.

I also want to tell you that we propose an online tools to display the BER/FER curves: http://aff3ct.github.io/comparator.html. You can load files from your computer like with `PyBER` and you also have pre-simulated references from `AFF3CT`.

I hope it helps.

**Comment by Shivani3094** [comment]
Thanks for your response. Yea it worked.
