### ISSUE TITLE
Data folder in pyBER is empty

### ISSUE THREAD

**Issue by Shivani3094** [aff3ct/PyBER#6]
Hi, 

I was trying to run PyBER in my PC and found that data in following links is empty:
https://github.com/aff3ct/PyBER/tree/master/data

Kindly update the refs so i can use this repositry.

Thanks 
Shivani

**Comment by kouchy** [comment]
Hi @Shivani3094,

I think the solution is the same as explained here : https://github.com/aff3ct/PyBER/issues/4#issuecomment-549026664.
The references are a submodule of the `PyBER` repo.
